# Generated by Django 3.1 on 2021-09-01 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='status',
            field=models.CharField(choices=[(1, 'Draft'), (2, 'Published'), (0, 'Withdrawn')], default=1, max_length=1),
        ),
    ]
